config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'

  resources :stories

  root 'dashboard#index'
end

app/models/application_record.rb
 class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord

  paginates_per 5
  validates :title, presence: true, length: { minimum: 3 }

  scope :published, ->   { where(published: true) }
  scope :not_published, -> { where(published: false) }
  scope :recent, -> { published.order(created_at: :desc).limit(10) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness:{ case_sensitive: false }
  validates :first_name, presence: true
  validates :last_name, presence: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @stories = Story.order(:title, :content).page(params[:page])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	def new
		@story = Story.new
	end

  def index
    @stories = Story.order(:title).page(params[:page])
  end

	def create
  	if @story.save
      redirect_to @story
    else
      render :new
    end
	end

	def show
    @story = Story.find(params[:id])
  end

  # TODO
  def edit
    @story = Story.find(params[:id])
  end

  def update
    story.update(story_params)
    story.save

    respond_with story

  end

  def destroy
    @story=Story.find(params[:id])
    @story.destroy

    flash.notice="Story '#{@story.title}' was deleted"

    redirect_to story_path
  end

	private

  def story_params
	 params.require(:story).permit(:title, :content)
	end
end

app/views/application/_navigation.slim
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a class="navbar-brand" href="/"
        = content_for?(:title) ? yield(:title) : "mazitov479"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      .nav.navbar-nav
        - if user_signed_in?
          = active_link_to "Dashboard", root_path, active: :exclusive, wrap_tag: :li
          = active_link_to "New story", new_story_path, active: :exclusive, wrap_tag: :li
          li.dropdown
            a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
              = "My blogs "
              span.caret
            ul.dropdown-menu role="menu"
              - if current_user.blogs.any?
                - current_user.blogs.each do |blog|
                  li = link_to blog.title, blog_path(url: blog.url)
                li.divider
              - else
              li = link_to "Create new blog", new_users_blog_path

      = render "navigation_user"

app/views/application/_navigation_user.slim
 ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    li.dropdown
      a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
        = "My account "
        span.caret
      ul.dropdown-menu role="menu"
        li = link_to "Settings", edit_user_registration_path
        li.divider
        li = link_to "Sign out", destroy_user_session_path, method: :delete
  - else
    = link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li

app/views/dashboard/_story.slim
.story-title
  = link_to @story.title, story
.story-footer
  .row
    .col-md-6.story-timestamp
      = l story.created_at, format: :default
    .col-md-6.story-actions
      .pull-right = link_to "Read more...", story

app/views/dashboard/index.html.slim
.row
  .col-12.col-lg-4
    #profile
      img class="portrait" src="https://sun9-28.userapi.com/c851232/v851232868/319c0/LJBsjLztfZY.jpg"

      .portrait-title
        h2 Камиль Мазитов
        h3 id="gray-h" Ruby on Rails junior-developer
        h3
          a class="text-muted" href="https://www.flatstack.com/" FlatStack

  .col-12.col-lg-8
    #biography
      h1 Biography
      p Kamil Mazitov lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed neque elit, tristique placerat feugiat ac, facilisis vitae arcu. Proin eget egestas augue. Praesent ut sem nec arcu pellentesque aliquet. Duis dapibus diam vel metus tempus vulputate.

      p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed neque elit, tristique placerat feugiat ac, facilisis vitae arcu. Proin eget egestas augue. Praesent ut sem nec arcu pellentesque aliquet. Duis dapibus diam vel metus tempus vulputate.

      .row
        .col-md-5
          h3 class="title3" Interests
          ul
            li Computer Science
            li Web development
            li Web design
            li Artificial intelligence

        .col-md-7
          h3 Education
          ul
            li
              div
                p class="course" Higher Institute of Information Technology and Intelligent Systems
                p class="institution" Kazan Federal University

.col-12.col-lg-4
  h1 Stories
  = paginate @stories

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title = content_for?(:title) ? yield(:title) + " | kamilmazitov" : "kamilmazitov"

    = csrf_meta_tags

    = stylesheet_link_tag "application", media: "all"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    = render "navigation"

    .container
      = yield

app/views/stories/_form.slim
= simple_form_for = simple_form_for(@story, html: { class: 'form-inline' }) do |f|
	.row

	  .col-12.col-lg-4
      	= f.label "Publish story or save it as draft?"
      	= f.input :published
	    = f.input :title, label: false, placeholder: "Title"
		= f.input :content, label: false, placeholder: 'Your story'
		= f.button :submit, class: "btn-lg"

app/views/stories/_story.slim
.story-title
  = link_to story.title, story
.story-footer
  .row
    .col-md-6.story-timestamp
      = l story.created_at, format: :default
    .col-md-6.story-actions
      .pull-right = link_to "Read more...", story

app/views/stories/edit.slim
.row
  .col-md-8.col-md-offset-2
    h1 Edit story

    = render "form"

app/views/stories/index.slim
.row
  .col-md-8.col-md-offset-2
    h1 Stories

    = render @stories

app/views/stories/new.slim
.row
  .col-md-8.col-md-offset-2
    h1 Create new story
    hr
    = render "form"

app/views/stories/show.slim
.row
  .col-md-8.col-md-offset-2
    .story data-story-id=@story.id
      .story-title
        = link_to @story.title, @story
      .story-content
        = @story.content.html_safe
      .story-footer
        .row
          .col-md-6.story-actions
              .pull-right = link_to "Edit", edit_story_path(@story)